"""
API routes for User_Role_Master table (APIs 1 & 2)
SELECT operations (API 1) and CRUD operations (API 2)
Updated: March 3, 2026 - roleId changed from VARCHAR(10) to SERIAL INTEGER
"""

from fastapi import APIRouter, Depends, HTTPException, Query, status
from datetime import datetime
from app.database import get_db
from app.services.user_role_service import UserRoleService
from app.schemas.user_role import UserRoleCreate, UserRoleUpdate, UserRoleResponse
from app.schemas.common import APIResponse
from app.constants import ErrorCodes, HTTPStatus

router = APIRouter(prefix="/roles", tags=["User Roles"])


# API 1: SELECT - Get all user roles
@router.get("/all", response_model=APIResponse)
async def get_all_roles(
    db=Depends(get_db),
    roleId: int = Query(None, ge=1, description="Fetch by specific Role ID (integer 1-8)"),
    status: str = Query(None, description="Filter by role status (Active, Inactive, Pending)"),
    limit: int = Query(100, ge=1, le=1000, description="Maximum number of records to return"),
    offset: int = Query(0, ge=0, description="Pagination offset")
):
    """
    API 1: SELECT Operation - Retrieve user roles with flexible filtering

    Supports three request scenarios:

    1. **Request with roleId parameter**:
       - Fetch all details for a specific role by ID
       - Role ID is an integer from 1 to 8
       - Example: ?roleId=1 → fetches ADMIN role, ?roleId=2 → fetches DOCTOR role

    2. **Request with status parameter**:
       - Fetch all roles with a specific status
       - Valid values: Active, Inactive, Closed, Pending
       - Example: ?status=Active → fetches all active roles

    3. **Request with no parameters**:
       - Fetch all roles from User_Role_Master table
       - Returns all columns and all rows irrespective of status
       - Example: /api/v1/roles/all → fetches all 8 roles

    Pagination: Use limit and offset parameters for result pagination
    """
    try:
        # Scenario 1: Fetch by specific Role ID
        if roleId:
            role = await UserRoleService.get_role_by_id(db, roleId)

            if not role:
                raise HTTPException(
                    status_code=HTTPStatus.NOT_FOUND,
                    detail=f"Role with ID {roleId} not found"
                )

            return APIResponse(
                status="success",
                code=HTTPStatus.OK,
                message=f"Role ID {roleId} retrieved successfully",
                data={"roles": [role], "count": 1, "scenario": "Fetch by Role ID"},
                timestamp=datetime.now()
            )

        # Scenario 2: Fetch by status or Scenario 3: Fetch all
        roles = await UserRoleService.get_all_roles(db, status, limit, offset)

        scenario_message = "Fetch all roles with status filter" if status else "Fetch all roles"
        detail_message = f"Retrieved {len(roles)} role(s) with status '{status}'" if status else "Retrieved all roles from User_Role_Master"

        return APIResponse(
            status="success",
            code=HTTPStatus.OK,
            message=detail_message,
            data={"roles": roles, "count": len(roles), "scenario": scenario_message},
            timestamp=datetime.now()
        )
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(
            status_code=HTTPStatus.INTERNAL_SERVER_ERROR,
            detail=str(e)
        )


# API 2: CRUD - Create role (Insert)
@router.post("", response_model=APIResponse, status_code=HTTPStatus.CREATED)
async def create_role(
    role: UserRoleCreate,
    db=Depends(get_db)
):
    """
    API 2: CRUD Operation - Insert new user role

    **Request Scenario: Insert New Role**

    Input required:
    - roleName: Human-readable role name (max 50 chars, must be unique)
    - status: Role status (Active, Inactive, Closed, or Pending)
    - comments: Optional description (max 250 chars)

    System-generated fields (auto-populated):
    - roleId: Auto-generated SERIAL INTEGER (auto-increment starting from 1)
    - createdDate: Set to current system date
    - updatedDate: Set to current system date

    Returns: Created role with all fields including auto-generated roleId and timestamps
    """
    try:
        # Check if role name already exists
        existing = await UserRoleService.role_exists_by_name(db, role.roleName)
        if existing:
            raise HTTPException(
                status_code=HTTPStatus.CONFLICT,
                detail=f"Role with name '{role.roleName}' already exists"
            )

        # Validate status is one of the allowed values
        allowed_statuses = ["Active", "Inactive", "Closed", "Pending"]
        if role.status not in allowed_statuses:
            raise HTTPException(
                status_code=HTTPStatus.BAD_REQUEST,
                detail=f"Status must be one of: {', '.join(allowed_statuses)}"
            )

        # Create role data (roleId will be auto-generated by SERIAL)
        role_data = role.dict()

        # createdDate and updatedDate are auto-set to current date in the service layer
        new_role = await UserRoleService.create_role(db, role_data)

        return APIResponse(
            status="success",
            code=HTTPStatus.CREATED,
            message="Role created successfully",
            data={
                "role": new_role,
                "scenario": "Insert new role",
                "info": "roleId auto-generated, createdDate and updatedDate set to current date"
            },
            timestamp=datetime.now()
        )
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(
            status_code=HTTPStatus.BAD_REQUEST,
            detail=str(e)
        )


# API 2: CRUD - Update role (Status and Comments Update)
@router.put("/{roleId}", response_model=APIResponse)
async def update_role(
    roleId: int,
    status_update: UserRoleUpdate,
    db=Depends(get_db)
):
    """
    API 2: CRUD Operation - Update user role

    **Request Scenario: Update Role Status and/or Comments**

    URL Parameter:
    - roleId: The role ID to update (integer from 1 to 8)

    Input required:
    - status: New status value (must be one of: Active, Inactive, Closed, Pending) - Optional
    - comments: New comments value (max 250 chars) - Optional

    System-managed fields:
    - updatedDate: Automatically set to current system date
    - Other fields (roleId, roleName): Cannot be updated through this endpoint

    Returns: Updated role with new status/comments and updated timestamp
    """
    try:
        # Check if role exists
        existing = await UserRoleService.get_role_by_id(db, roleId)
        if not existing:
            raise HTTPException(
                status_code=HTTPStatus.NOT_FOUND,
                detail=f"Role with ID {roleId} not found"
            )

        # Build update data from provided fields
        update_data = {}

        if status_update.status is not None:
            # Validate status is one of the allowed values
            allowed_statuses = ["Active", "Inactive", "Closed", "Pending"]
            if status_update.status not in allowed_statuses:
                raise HTTPException(
                    status_code=HTTPStatus.BAD_REQUEST,
                    detail=f"Status must be one of: {', '.join(allowed_statuses)}. Received: '{status_update.status}'"
                )
            update_data["status"] = status_update.status

        if status_update.comments is not None:
            update_data["comments"] = status_update.comments

        if not update_data:
            raise HTTPException(
                status_code=HTTPStatus.BAD_REQUEST,
                detail="Request body must contain at least one field: 'status' or 'comments'"
            )

        # Update the role
        updated_role = await UserRoleService.update_role(db, roleId, update_data)

        return APIResponse(
            status="success",
            code=HTTPStatus.OK,
            message=f"Role ID {roleId} updated successfully",
            data={
                "role": updated_role,
                "scenario": "Update role status/comments",
                "info": "updatedDate set to current date. Fields roleId and roleName cannot be modified."
            },
            timestamp=datetime.now()
        )
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(
            status_code=HTTPStatus.BAD_REQUEST,
            detail=str(e)
        )
